Ch 445
GoodRequest/spongly-dapp-public pull request #117
Opened 2023-10-24 11:35 UTC by daniel-hlavaty

2023-10-25 10:41 UTC, michalbella requested changes

2023-10-25 10:41 UTC, michalbella commented on src/components/statisticRow/TicketStatisticRow.tsx
> +						<StatisticCard showMobileInColumn={true} isLoading={isLoading} value={buyIn} title={t('Buy in')} addMobileBackground={true} />
Buy in -> Buy-in

2023-10-25 10:41 UTC, michalbella commented on src/components/statisticRow/UserStatisticRow.tsx
>  							value={isMounted ? `${user?.successRate ? user.successRate : 0} %` : ''}
do we need this checking for isMounted ? because this check is above where you check whole component render only if isMounted.

2023-10-25 10:41 UTC, michalbella commented on src/components/ticketList/TicketList.tsx
> +											<Sorter title={t('Buy in')} name={TICKET_SORTING.BUY_IN} />
also this should be Buy-in not Buy in

2023-10-25 10:41 UTC, michalbella commented on src/content/ticketDetailContent/TicketDetailContent.tsx
> +			{(positionsData || ticketData || isLoading) && (
i dont think i understand those conditions. Why we render something and condition is set to isLoading is true? I think inside TicketStatisticRow is some skeleton which trigger if is loading is true?

2023-10-25 10:41 UTC, michalbella commented on src/styles/GlobalStyles.ts
> +export const FlagWorldBig = styled.div`
are you using this somewhere?

2023-10-25 11:35 UTC, daniel-hlavaty commented on src/atoms/statisticCard/StatisticCard.tsx
> +			{img && <SC.Image filled={filled} src={img} />}
ill skip this, since we are only using it for wallet logos that have default

2023-10-25 11:44 UTC, daniel-hlavaty commented on src/atoms/statisticCard/StatisticCard.tsx
>  						<SC.FirstAddressPart>{String(value)?.substring(0, String(value).length - 3)}</SC.FirstAddressPart>
@michalbella Its on purpose, so walletadress is never fully shown

2023-10-25 11:45 UTC, daniel-hlavaty commented on src/atoms/statisticCard/StatisticCardStyles.tsx
> +export const StatisticCard = styled.div<{ filled: boolean; showMobileInColumn: boolean; addMobileBackground: boolean }>`
its used on line 28

2023-10-26 05:52 UTC, michalbella approved these changes

2023-10-26 05:52 UTC, merged