CH-549
GoodRequest/spongly-dapp-public pull request #126
Opened 2023-10-31 11:41 UTC by michalbella

2023-10-31 11:49 UTC, daniel-hlavaty requested changes

2023-10-31 11:49 UTC, daniel-hlavaty commented on src/components/connectButton/ConnectButton.tsx
> +													{/* // TODO: if next network will be added need to be conditionaly rendered icon */}
Wasnt the optimism icon we used before... more sexy?

2023-10-31 11:49 UTC, daniel-hlavaty commented on src/utils/constants.ts
> +	// NOTE: Motosport is currently not available
doesnt this only remove the option from filter? Why is it unavailable, should its matches even be shown in list?

2023-11-01 21:09 UTC, michalbella commented on src/utils/constants.ts
> +	// NOTE: Motosport is currently not available
I just copied. this logic from Thales and yes I just dont want this sport in Filter until sezon starts.

2023-11-01 21:10 UTC, michalbella commented on src/components/connectButton/ConnectButton.tsx
> +													{/* // TODO: if next network will be added need to be conditionaly rendered icon */}
yeah this is more red and sexy :)

2023-11-01 21:10 UTC, merged